name: NodeJS with Grunt CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Enable caching for faster installs

    - name: Install dependencies
      run: npm ci  # Uses package-lock.json for reproducible builds

    - name: Run Grunt build
      run: grunt build  # Assuming you have a 'build' task in Gruntfile

    - name: Run Grunt tests (if you have tests)
      run: grunt test  # Add this if you have test tasks in Grunt
